# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 42585ab8854582ba98415670de1348f6d8ecb76c5f5f5c7a88a372d983cd333ff80ee14dedbd1503d736575c86f48e2dbdd1f834d5b64712c78cfd38c4ac86a3

test:
  secret_key_base: 9c3d04c1935f8c873851ba3b85eb69551506a6304fd6dc746be37608e1b30aedff4dffc1e43327e120bb8f1f247cdf5dbeeec2c918a9093cb15a6b007f35289f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
